name: 'Linear App'
description: 'Create a comment in a linear ticket'
inputs:
  message:  # message to post in comment
    description: 'message to create'
    required: true
    default: 'I am a robot'
  title:
    description: 'topic title'
    required: false
    default: ''
  team:
    description: 'team'
    required: false
    default: ''
  label:
    description: 'label'
    required: false
    default: ''
  state:
    description: 'ticket state'
    required: false
    default: 'Draft'
outputs:
  time: # time of output
    description: 'The time we created comment'
runs:
  using: 'node12'
  main: 'app.js'
