name: 'Linear App'
description: 'Create a comment in a linear ticket'
inputs:
  message:  # message to post in comment
    description: 'message to create'
    required: true
    default: 'Hello'
outputs:
  time: # time of output
    description: 'The time we created comment'
runs:
  using: 'node12'
  main: 'app.js'